### ISSUE TITLE
<C-N> (word completion) exception in VS 2019

### ISSUE THREAD

**Issue by fen** [VsVim/VsVim#2466]
Starting in Preview 3 I'm seeing this `NotImplementedException` when doing word completion.

```
System.NotImplementedException: Please use $IAsyncCompletionBroker and IAsyncCompletionSession to interact with completion. Use IAsyncCompletionBroker.IsCompletionSupported to check if feature is available and IAsyncCompletionBroker.GetSession to get the session.
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.ShimCompletionSession.set_SelectedCompletionSet(CompletionSet value)
   at Vim.UI.Wpf.Implementation.WordCompletion.WordCompletionSessionFactoryService.Vim.IWordCompletionSessionFactoryService.CreateWordCompletionSession(ITextView textView, SnapshotSpan wordSpan, IEnumerable`1 wordCollection, Boolean isForward)
   at Vim.Modes.Insert.InsertMode.StartWordCompletionSession(Boolean isForward)
   at Vim.Modes.Insert.InsertMode.ProcessWordCompletionNext(KeyInput keyInput)
   at <StartupCode$Vim-Core>.$Modes_Insert_InsertMode.regularCommands@325-3.Invoke(KeyInput arg00)
   at Vim.Modes.Insert.InsertMode.ProcessCore(KeyInput keyInput)
   at Vim.Modes.Insert.InsertMode.Process(KeyInput keyInput)
   at Vim.Modes.Insert.InsertMode.Vim-IMode-Process(KeyInput keyInput)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput)
   at <StartupCode$Vim-Core>.$VimBuffer.processSet@590.Invoke(KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by jaredpar** [comment]
Thanks for reporting. I saw that as well. That is going to be tricky to implement correctly.

**Comment by jaredpar** [comment]
Found the tutorial for adding async completion.

https://github.com/microsoft/vs-editor-api/wiki/Modern-completion-walkthrough

Looks straight forward. A bit awkward because it's not available in VS2015 and most of VS2017. That means we'll need to push it to the VS specific layer. Still looks fairly doable though. Hope to get to implementing that this weekend.

**Comment by jaredpar** [comment]
Hmm a bit less straight forward than I thought. I initially thought I could re-use a lot of the completion layer from the old APIs. Turns out I can re-use basically zero of it. Have to rewrite it from scratch and the docs are a bit out of date. 

Good news is I figured out the basics here. I can get the word completion showing and committing properly. But none of the keyboard commands are hooked. Will need a bit of help from VS team to get this working. But still pretty doable before RTM.

**Comment by jaredpar** [comment]
Took another stab at this today. The docs are just not complete enough to make a full implementation. Reaching out to editor team to see if someone can sit down with me for a bit to help get through this.

**Comment by jaredpar** [comment]
Looks like at the least I need to get myself ahead of Roslyn in the `IAsyncCompletionSourceProvider` chain

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/IntelliSense/AsyncCompletion/CompletionSourceProvider.cs,14

**Comment by ricksladkey** [comment]
This works correctly again in the released version of VS2019 with no changes to VsVim. As a result, I've changed this from a bug to a feature request.

**Comment by fen** [comment]
I still see this exception in `16.0.3` (community).

**Comment by ricksladkey** [comment]
@fen, I tested basic `<C-n>`/`<C-p>` completion and it worked fine, but with more testing I was also able to repro the exception. This is odd because the gist of the error message is that non-async completion is absolutely forbidden with VS2019, but the reality is that it is sometimes allowed.

The simple case I first tested was File -> New -> Text File and type some words:

```
abc def
ghi jkl
```

and then enter insert mode and press `<C-n>`. This works just how it worked in VS2017 and earlier, that is no exception is raised and no completion shim is involved. But a similar experiment on a C# file does repro the exception.

This seems to imply that there is a certain amount of "latitude" with respect to enforcing the new async completion, which, ideally, we could get to apply all the time. At least until we get the async completion implemented. 

In any case, I will restore the bug label.

**Comment by fen** [comment]
Interesting can confirm that I see the same behavior `.txt` file completion working same for markdown.

**Comment by jaredpar** [comment]
@ricksladkey i believe the completion kind, sync vs async, is dependent on the content type of the active buffer. For C# it's always async but for other kinds it can still be the sync provider. 

Good news is I mostly have the async support working now. It's unfortunately less featurefull than sync completion (no wrap around support) but the overall workflow is working. This weekend I'll be working through my BUILD talk but plan is to get it merged mid / late next week.
