### ISSUE TITLE
VimWpf unit tests crashing in CI

### ISSUE THREAD

**Issue by jaredpar** [VsVim/VsVim#2574]
**Describe the bug**
The VimWpf unit tests are causing xunit to crash during `AppDomain` unload from time to time with the following stack track:

```
   Vim.UI.Wpf.UnitTest  Total: 154, Errors: 0, Failed: 0, Skipped: 0, Time: 9.173s
xUnit.net Console Runner (32-bit Desktop .NET 4.0.30319.42000)
  Discovering: Vim.VisualStudio.Shared.UnitTest
  Discovered:  Vim.VisualStudio.Shared.UnitTest
  Starting:    Vim.VisualStudio.Shared.UnitTest
  Finished:    Vim.VisualStudio.Shared.UnitTest
System.ComponentModel.Win32Exception (0x80004005): Invalid window handle
   at MS.Win32.ManagedWndProcTracker.HookUpDefWindowProc(IntPtr hwnd)
   at MS.Win32.ManagedWndProcTracker.OnAppDomainProcessExit()
   at MS.Win32.ManagedWndProcTracker.ManagedWndProcTrackerShutDownListener.OnShutDown(Object target, Object sender, EventArgs e)
   at MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)
```

**To Reproduce**
Run the VimWpf unit tests in a loop and this will eventually happen.

**Expected behavior**
Unit Tests pass without error.

**Additional context**
This has been reported in other projects that test WPF in xunit inside an `AppDomain`

- https://github.com/dotnet/roslyn/issues/3396
- https://github.com/dotnet/roslyn/issues/9247
- https://github.com/dotnet/roslyn/issues/26842

The underlying problem is a bug in WPF: this exception should not be propagating out. But it's in the framework so not going to be fixed anytime soon. Pretty sure this is coming because we have a race between the finalizer and the `AppDomain.Unload` code paths. Need to more aggressively clean up the HWND values when shutting down the `Dispatcher` to prevent this from happening.

**Comment by jaredpar** [comment]
Locally on debug builds of the VS2017 editor I find this happens ~20% of the time.

**Comment by jaredpar** [comment]
Doh. This is because I don't have the correct fix for `StaContext` in the branch I was working in. It was missing the `StaThread.Join` call in `StaContext.Dispose`. Add that back in and it clears things up.
