### ISSUE TITLE
Exception encountered in visual selection tracker

### ISSUE THREAD

**Issue by ricksladkey** [VsVim/VsVim#2618]
I'm not quite sure what I typed, but I encountered an exception while fat-fingering some command sequence ending in `<Esc>`. Here is the output of the activity log.

```
  <entry>
    <record>1328</record>
    <time>2019/06/09 17:58:23.078</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: end
   at Microsoft.VisualStudio.Text.VirtualSnapshotSpan..ctor(VirtualSnapshotPoint start, VirtualSnapshotPoint end)
   at Vim.VisualSelection.AdjustForSelectionKind(SelectionKind selectionKind)
   at Vim.Modes.Visual.SelectionTracker.UpdateSelection()
   at Vim.Modes.Visual.SelectionTracker.Vim-Modes-Visual-ISelectionTracker-UpdateSelection()
   at Vim.Modes.Visual.VisualMode.Process(KeyInputData keyInputData)
   at Vim.Modes.Visual.VisualMode.Vim-IMode-Process(KeyInputData keyInputData)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput, Boolean wasMapped)
   at <StartupCode$Vim-Core>.$VimBuffer.processSet@598.Invoke(KeyInputSet keyInputSet, Boolean wasMapped)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at <StartupCode$Vim-Core>.$VimBuffer.processUnmappedSet@603.Invoke(KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
  <entry>
    <record>1329</record>
    <time>2019/06/09 17:58:23.561</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: end
   at Microsoft.VisualStudio.Text.VirtualSnapshotSpan..ctor(VirtualSnapshotPoint start, VirtualSnapshotPoint end)
   at Vim.VisualSelection.AdjustForSelectionKind(SelectionKind selectionKind)
   at Vim.Modes.Visual.SelectionTracker.UpdateSelection()
   at Vim.Modes.Visual.SelectionTracker.Vim-Modes-Visual-ISelectionTracker-UpdateSelection()
   at Vim.Modes.Visual.VisualMode.Process(KeyInputData keyInputData)
   at Vim.Modes.Visual.VisualMode.Vim-IMode-Process(KeyInputData keyInputData)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput, Boolean wasMapped)
   at <StartupCode$Vim-Core>.$VimBuffer.processSet@598.Invoke(KeyInputSet keyInputSet, Boolean wasMapped)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at <StartupCode$Vim-Core>.$VimBuffer.processUnmappedSet@603.Invoke(KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.TryProcessWithBuffer(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Exec(EditCommand editCommand, Action& preAction, Action& postAction)
   at Vim.VisualStudio.Implementation.Misc.StandardCommandTarget.Vim.VisualStudio.ICommandTarget.Exec(EditCommand editCommand, Action& preAction, Action& postAction)
   at Vim.VisualStudio.VsCommandTarget.Exec(EditCommand editCommand, Action& preAction, Action& postAction)
   at Vim.VisualStudio.VsCommandTarget.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& commandGroup, UInt32 commandId, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.Intellisense.MultiCaretPreemptingFilterProvider.MultiCaretPreemptingFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam)
   at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
  <entry>
    <record>1330</record>
    <time>2019/06/09 17:58:23.575</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: end
   at Microsoft.VisualStudio.Text.VirtualSnapshotSpan..ctor(VirtualSnapshotPoint start, VirtualSnapshotPoint end)
   at Vim.VisualSelection.AdjustForSelectionKind(SelectionKind selectionKind)
   at Vim.Modes.Visual.SelectionTracker.UpdateSelection()
   at Vim.Modes.Visual.SelectionTracker.Vim-Modes-Visual-ISelectionTracker-UpdateSelection()
   at Vim.Modes.Visual.VisualMode.Process(KeyInputData keyInputData)
   at Vim.Modes.Visual.VisualMode.Vim-IMode-Process(KeyInputData keyInputData)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput, Boolean wasMapped)
   at <StartupCode$Vim-Core>.$VimBuffer.processSet@598.Invoke(KeyInputSet keyInputSet, Boolean wasMapped)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at <StartupCode$Vim-Core>.$VimBuffer.processUnmappedSet@603.Invoke(KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessor.TryProcess(KeyInput keyInput)
   at Vim.UI.Wpf.VimKeyProcessor.TextInput(TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

For future reference, here is a shell command that massages the activity log so that it appears more readable to humans:

```
sed -e "s/&#x000D;&#x000A;/\n/g" -e "s/&gt;/>/g" -e "s/&lt;/</g" -e "s/&amp;/\&/g"
```

**Comment by ricksladkey** [comment]
From the stack trace, and from the exception, it is clear that the virtual end point of the virtual snapshot span is **before** the start point. It's not immediately obvious how that could happen because we attempt to protect against that situation, see:

```f#
                    // The span decreases by a single character in exclusive
                    let characterSpan =
                        let endPoint = characterSpan.VirtualLast |> OptionUtil.getOrDefault characterSpan.VirtualStart
                        CharacterSpan(VirtualSnapshotSpan(characterSpan.VirtualStart, endPoint), characterSpan.UseVirtualSpace)
                    VisualSelection.Character (characterSpan, path)
```

**Comment by ricksladkey** [comment]
Here is the evidence that the end is before the beginning, from:

```
#region Assembly Microsoft.VisualStudio.Text.Logic, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Build\VsVim\References\Vs2019\Microsoft.VisualStudio.Text.Logic.dll
#endregion
```

```c#
		public VirtualSnapshotSpan(VirtualSnapshotPoint start, VirtualSnapshotPoint end)
		{
			if (start.Position.Snapshot == null || end.Position.Snapshot == null)
			{
				throw new ArgumentException("The VirtualSnapshotPoint is not initialized.");
			}
			if (start.Position.Snapshot != end.Position.Snapshot)
			{
				throw new ArgumentException("The specified VirtualSnapshotPoints belong to different ITextSnapshots.");
			}
			if (end < start)
			{
				throw new ArgumentOutOfRangeException("end");
			}
			this._start = start;
			this._end = end;
		}
```

**Comment by jaredpar** [comment]
I suspect the bug is in `CharacterSpan.VirtualLast`. There doesn't seem to be any protection against cases where the character span is one or zero characters. For that I'm guessing there is a way to get `VirtualLast` to be before `VirtualStart` and hence get into this situation.

**Comment by ricksladkey** [comment]
OK, this issue bubbled up to the top of my list.

Here is the code for `CharacterSpan.VirtualLast`:

```f#
    member x.VirtualLast =
        let endPoint: VirtualSnapshotPoint = x.VirtualEnd
        if endPoint = x.VirtualStart then
            None
        else
            endPoint
            |> VirtualSnapshotPointUtil.GetPreviousCharacterSpanWithWrap
            |> Some
```

This code must be particularly confusing to a newcomer because there are two different kinds of `CharacterSpan` objects referred to in the same function!

I remember writing that code when I was adding support for virtual edit. The idea is that it **should** work if the start and end points point to valid caret positions, i.e. between Unicode character spans.

You are right that the previous character span is not certain to be one character, but since the `start <> end`, this means that it has to be **two** characters and so `start < end` but `start > end - 2`.  I will try to concoct a buffer that triggers this mess.

**Comment by ricksladkey** [comment]
Yes, that is the problem. This code:

```f#
    let GetCharacterSpan (line: ITextSnapshotLine) (point: SnapshotPoint) = 
        if IsInsideLineBreak point line then
            new SnapshotSpan(line.End, line.EndIncludingLineBreak)
        ...
```

If the point is in-between the CR and the LF of a `<CR><LF>` line terminator, the point will get warped back to the beginning of the linebreak (exactly like caret affinity), and then one more position will be subtracted. So if start points to the beginning of the linebreak and end points between the linebreak characters, then virtual end will point to the last character of the line, which is before start.

If the line is empty and the previous line also ends with `<CR><LF>`, this will subtract **three**: one for the initial warping and two for the previous linebreak.
