### ISSUE TITLE
[VsMac] Editing XAML often breaks VIM modes, inserting characters instead of making actions (e.g.: x inserts x instead of removing character)

### ISSUE THREAD

**Issue by idchlife** [VsVim/VsVim#2791]
**Describe the bug**

**To Reproduce**

0. Choose key bindings Visual Studio for Mac.
1.  Create new Xamarin Forms project, blank application
2.  Open MainPage.xaml
3.  Go to insert mode, press backspace (it does not work but it's OK with me since it's usually and anitpattern when using vim to rely on old keybindings)
4.  Press Esc, try to remove character with x. See, that visually you are in Normal mode, but x characters iserted where caret is.
5. Try to press Esc multiple times, no luck. HJKL works, though, which breaks overall workflow and makes everything kinda messy and confusing.
6. Try to delete line with dd, which inserts d characters instead of deleting line.
7. Restart VsMac to remove this behaviour.
8. There can be possibility to play around for a bit with XAML trying to use backspace and jump back and forth between mods, because sometimes it works fine and then just breaks forever and you need either to close-open file or restart VsMac.

**Expected behavior**
It is expected to exit insert mode and have normal behaviour of functional keys.

**Screenshots**

**Environment (please complete the following information):**

- Visual Studio version: VsMac 8.5 build 2987
- VsVim version: 2.8.0.1
- Programming Language: XAML
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**

Note:
The following is written about contributing.
https://github.com/VsVim/VsVim/blob/master/CONTRIBUTING.md

General Keyboard configuration problems are described below.
https://github.com/VsVim/VsVim/issues/2527

**Comment by nosami** [comment]
VsMac is still using the old editor for editing XAML files and VsVim only works with the new editor. This will change soon in a newer version of VsMac.

You might be able to get Vim support in XAML by installing the XSVim extension which works with the old editor.

**Comment by nosami** [comment]
@idchlife are you using `set backspace=indent,eol,start` in your `~/.vsvimrc`?

**Comment by idchlife** [comment]
@nosami oh, I don't use ~/.vsvimrc

Maybe it was my mistake, using without .vsvimrc? Should I add this line to it and try again?

**Comment by nosami** [comment]
It won't hurt :)

This is mine. mapleader doesn't seem to be working for some reason though.

```vim
set incsearch
set hlsearch
let mapleader=" "
set cursorline
set clipboard=unnamed
set expandtab
set ignorecase
set smartcase
set autoindent
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4
nnoremap <C-p> :vsc MonoDevelop.Ide.Commands.SearchCommands.GotoFile <CR>
nnoremap gu :vsc MonoDevelop.Refactoring.RefactoryCommands.FindReferences <CR>
nnoremap gh :vsc MonoDevelop.Ide.Commands.TextEditorCommands.ShowQuickInfo <CR>
nnoremap gb :vsc MonoDevelop.RefactoryCommands.NavigationCommands.FindBaseSymbols <CR>
nnoremap <C-w>o :vsc MonoDevelop.Ide.Commands.FileTabCommands.CloseAllButThis <CR>
" I prefer default VSMac behaviour of navigating between buffers
" when navigating backwards and forwards
nnoremap <C-o> :vsc MonoDevelop.Ide.Commands.NavigationCommands.NavigateBack <CR>
nnoremap <C-i> :vsc MonoDevelop.Ide.Commands.NavigationCommands.NavigateForward <CR>
" Keys copied from SpaceMacs
nnoremap <Space>p :vsc MonoDevelop.Ide.Commands.SearchCommands.GotoFile <CR>

nmap gs :vsc VsVim.ShowPadByTitle Solution<CR>

```

**Comment by nosami** [comment]
@idchlife did that help? I don't think that it should, I just wanted to rule it out as a possibility.

**Comment by idchlife** [comment]
@nosami sorry, I did create and add 1 line into .vsvimrc file and now taking time testing this. So far so good but not yet closing issue because I developed a habit of not pressing backspace in VsMac because of my situation :D 
Will try to use it to test more.

**Comment by idchlife** [comment]
@nosami I got another one. Pressed X in normal mode and got x inserted, only VsMac restart helped.

I don't think I have adequate data, though. VsMac was updated once during this period and maybe it affected somehow bug or lack of one.

Maybe I can save and show some kind of logs?

Also I will try to record keystrokes via Karabiner EventViewer, maybe this will help to recreate bug.

P.S. I suspect .vsvimrc line actually helped to reduce bug to minimum. Only 1 occurence in 1 week. I think I pressed another key like backspace or something.

**Comment by nosami** [comment]
@idchlife maybe there is something in the IDE log that may help. Have a look at the `Help -> Open Log Directory` menu item and then look for the IDE.log file from around the time the crash happened.

**Comment by idchlife** [comment]
@nosami I got the bug again. Here is the latest log around bug:

```log

INFO [2020-03-05 20:50:44Z]: [2020-03-05 20:50:44.1] ERROR: : Error ending telemetry scoped event
System.InvalidOperationException: The scoped user task is already ended.
  at Microsoft.VisualStudio.Telemetry.TelemetryScope`1[T].End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String resultSummary) [0x00010] in <65f1ff5884d54c33bd42db70da4ab4b5>:0 
  at Xamarin.Designer.Telemetry.VsTelemetry.VsTelemetryService+UserTaskScope.End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String summary, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00020] in /Users/runner/runners/2.164.7/work/1/s/Xamarin.Designer/Xamarin.Designer/Telemetry/VsTelemetry/UserTaskScope.cs:75 

INFO [2020-03-05 20:50:52Z]: [2020-03-05 20:50:52.3] ERROR: : Error ending telemetry scoped event
System.InvalidOperationException: The scoped user task is already ended.
  at Microsoft.VisualStudio.Telemetry.TelemetryScope`1[T].End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String resultSummary) [0x00010] in <65f1ff5884d54c33bd42db70da4ab4b5>:0 
  at Xamarin.Designer.Telemetry.VsTelemetry.VsTelemetryService+UserTaskScope.End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String summary, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00020] in /Users/runner/runners/2.164.7/work/1/s/Xamarin.Designer/Xamarin.Designer/Telemetry/VsTelemetry/UserTaskScope.cs:75 
INFO [2020-03-05 20:50:52Z]: [2020-03-05 20:50:52.3] ERROR: : Error ending telemetry scoped event
System.InvalidOperationException: The scoped user task is already ended.
  at Microsoft.VisualStudio.Telemetry.TelemetryScope`1[T].End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String resultSummary) [0x00010] in <65f1ff5884d54c33bd42db70da4ab4b5>:0 
  at Xamarin.Designer.Telemetry.VsTelemetry.VsTelemetryService+UserTaskScope.End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String summary, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00020] in /Users/runner/runners/2.164.7/work/1/s/Xamarin.Designer/Xamarin.Designer/Telemetry/VsTelemetry/UserTaskScope.cs:75 

INFO [2020-03-05 20:51:05Z]: [2020-03-05 20:51:05.1] ERROR: : Error ending telemetry scoped event
System.InvalidOperationException: The scoped user task is already ended.
  at Microsoft.VisualStudio.Telemetry.TelemetryScope`1[T].End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String resultSummary) [0x00010] in <65f1ff5884d54c33bd42db70da4ab4b5>:0 
  at Xamarin.Designer.Telemetry.VsTelemetry.VsTelemetryService+UserTaskScope.End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String summary, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00020] in /Users/runner/runners/2.164.7/work/1/s/Xamarin.Designer/Xamarin.Designer/Telemetry/VsTelemetry/UserTaskScope.cs:75 
INFO [2020-03-05 20:51:05Z]: [2020-03-05 20:51:05.1] ERROR: : Error ending telemetry scoped event
System.InvalidOperationException: The scoped user task is already ended.
  at Microsoft.VisualStudio.Telemetry.TelemetryScope`1[T].End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String resultSummary) [0x00010] in <65f1ff5884d54c33bd42db70da4ab4b5>:0 
  at Xamarin.Designer.Telemetry.VsTelemetry.VsTelemetryService+UserTaskScope.End (Microsoft.VisualStudio.Telemetry.TelemetryResult result, System.String summary, System.Collections.Generic.Dictionary`2[TKey,TValue] properties) [0x00020] in /Users/runner/runners/2.164.7/work/1/s/Xamarin.Designer/Xamarin.Designer/Telemetry/VsTelemetry/UserTaskScope.cs:75 
INFO [2020-03-05 21:31:44Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmpd905a90.tmp
INFO [2020-03-05 21:31:47Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp2e0cd1a1.tmp
text/uri-list:
file:///Users/idchlife/Downloads/Fonts/StagSansLC-Book.otf
file:///Users/idchlife/Downloads/Fonts/StagSansLC-Light.otf
file:///Users/idchlife/Downloads/Fonts/StagSansLC-Medium.otf

INFO [2020-03-05 21:31:56Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp43977229.tmp
INFO [2020-03-05 21:31:58Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp425a48ef.tmp
WARNING [2020-03-05 21:40:15Z]: Slow command update (52ms): Command:MonoDevelop.Ide.Commands.ViewCommands.OpenWithList, Method:MonoDevelop.Ide.Gui.Pads.ProjectPad.ProjectFileNodeCommandHandler.OnOpenWithUpdate, CommandTargetType:MonoDevelop.Ide.Gui.Pads.ProjectPad.ProjectFileNodeCommandHandler
INFO [2020-03-05 21:40:19Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp55978552.tmp
INFO [2020-03-05 21:40:21Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp66b3695f.tmp
text/uri-list:
file:///Users/idchlife/Downloads/KV.png

INFO [2020-03-05 21:40:26Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp7eb30124.tmp
INFO [2020-03-05 21:40:27Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp601587ef.tmp
INFO [2020-03-05 21:41:19Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp4f257cfb.tmp
INFO [2020-03-05 21:41:20Z]: Found Xamarin.iOS, version 13.14.1.39.
Simulator configuration written to /var/folders/t5/gr8ck1dn1918xphmxnn3s0c00000gn/T/tmp21e331b7.tmp
```

**Comment by aaronlabeau** [comment]
This breaks for me a lot.  Is there any thing I can turn on in logging to help figure out why it's happening.  It's really random - sometimes I can go an hour editing various files before it breaks in XAML files only and sometimes it's the first XAML file I open.  When this does happen I have to completely close and open Visual Studio to fix it.

**Comment by nosami** [comment]
Are there any exceptions in your log file from around the time it broke?

**Comment by idchlife** [comment]
@nosami that's the odd thing. There are exceptions just about usual stuff in VsMac: simulator connection problems, render problems etc.

I suspect this is kind of evasive bug that does not produce errors since there is some workflow hiccups but overall plugin "thinks" it behaves normally. I think I will try to repro it within several days using clean project, so we can catch it.

**Comment by aaronlabeau** [comment]
@nosami  so when this happens to me if I look at the logs I see:

ERROR [2020-03-08 13:45:06Z]: Failed assertion: EndPosition must be equal or greater than StatementEndPosition!
   at Microsoft.VisualStudio.LanguageServices.Xaml.LanguageService.XamlSource.CreateXamlElementStructureTagger(XamlLanguageService.LanguageService.StructureVisualizer.XamlStructureTag parentTag, ITextSnapshot snapshot, Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XmlElement element, System.Collections.Generic.Stack`1 regionStack, CancellationToken cancellationToken) in /Users/runner/runners/2.164.3/work/1/s/Xamarin.Designer.Forms/XamlLanguageService/XamlLanguageService/LanguageService/XamlSource.cs:line 559
   at Microsoft.VisualStudio.LanguageServices.Xaml.LanguageService.XamlSource.CreateXamlElementStructureTagger(XamlLanguageService.LanguageService.StructureVisualizer.XamlStructureTag parentTag, ITextSnapshot snapshot, Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XmlElement element, System.Collections.Generic.Stack`1 regionStack, CancellationToken cancellationToken) in /Users/runner/runners/2.164.3/work/1/s/Xamarin.Designer.Forms/XamlLanguageService/XamlLanguageService/LanguageService/XamlSource.cs:line 634
   at Microsoft.VisualStudio.LanguageServices.Xaml.LanguageService.XamlSource.CreateXamlElementStructureTagger(XamlLanguageService.LanguageService.StructureVisualizer.XamlStructureTag parentTag, ITextSnapshot snapshot, Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XmlElement element, System.Collections.Generic.Stack`1 regionStack, CancellationToken cancellationToken) in /Users/runner/runners/2.164.3/work/1/s/Xamarin.Designer.Forms/XamlLanguageService/XamlLanguageService/LanguageService/XamlSource.cs:line 634
   at Microsoft.VisualStudio.LanguageServices.Xaml.LanguageService.XamlSource.CreateXamlElementStructureTagger(XamlLanguageService.LanguageService.StructureVisualizer.XamlStructureTag parentTag, ITextSnapshot snapshot, Microsoft.VisualStudio.DesignTools.Xaml.LanguageService.Semantics.XmlElement element, System.Collections.Generic.Stack`1 regionStack, CancellationToken cancellationToken) in /Users/runner/runners/2.164.3/work/1/s/Xamarin.Designer.Forms/XamlLanguageService/XamlLanguageService/LanguageService/XamlSource.cs:line 634
   at Microsoft.VisualStudio.LanguageServices.Xaml.LanguageService.XamlSource.CreateXamlStructureTagger(XamlLanguageService.LanguageService.StructureVisualizer.XamlStructureTag parentTag, ITextSnapshot snapshot, CancellationToken token) in /Users/runner/runners/2.164.3/work/1/s/Xamarin.Designer.Forms/XamlLanguageService/XamlLanguageService/LanguageService/XamlSource.cs:line 536
   at XamlLanguageService.LanguageService.StructureVisualizer.XamlStructureTagger+BackgroundScan+<>c__DisplayClass1_0.<.ctor>b__0() in /Users/runner/runners/2.164.3/work/1/s/Xamarin.Designer.Forms/XamlLanguageService/XamlLanguageService/LanguageService/StructureVisualizer/XamlStructureTagger.cs:line 153
   at System.Threading.Tasks.Task.InnerInvoke() in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2476
   at System.Threading.Tasks.Task.Execute() in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2319
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object obj) in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2463
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:line 968
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:line 910
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef currentTaskSlot) in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/corert/Task.cs:line 72
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution) in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2385
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2334
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:line 899
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:line 1261
INFO [2020-03-08 13:45:08Z]: Processing references for project 'EY.Mobile.TestApp.Forms.iOS' for the designer
INFO [2020-03-08 13:45:08Z]: Processing references for project 'EY.Mobile.TestApp.Forms' for the designer
INFO [2020-03-08 13:45:11Z]: Processing references for project 'EY.Mobile.TestApp.Forms.iOS' for the designer
INFO [2020-03-08 13:45:11Z]: Processing references for project 'EY.Mobile.TestApp.Forms' for the designer
INFO [2020-03-08 13:45:50Z]: AMDevice: Aaron iPhone 11 Pro: 00008030-00154DE90C40802E
WARNING [2020-03-08 13:46:57Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
WARNING [2020-03-08 13:46:57Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
WARNING [2020-03-08 13:46:57Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
WARNING [2020-03-08 13:46:58Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
WARNING [2020-03-08 13:46:58Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
WARNING [2020-03-08 13:46:58Z]: Failed to get filename of textbuffer, breakpoints integration will not work.

ERROR [2020-03-08 13:55:38Z]: An unhandled exception has occurred. Terminating Visual Studio? False
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: GetTextViewLineContainingBufferPosition called after the view is closed
  at Microsoft.VisualStudio.Text.Editor.Implementation.BaseTextView.GetTextViewLineContainingBufferPosition (Microsoft.VisualStudio.Text.SnapshotPoint bufferPosition) [0x001a0] in /Users/runner/runners/2.165.0/work/1/s/main/external/vs-editor-core/src/Editor/Text/Impl/BaseViewImpl/BaseTextView.cs:763 
  at Microsoft.VisualStudio.Text.Editor.Implementation.TextSelection.NormalizePoint (Microsoft.VisualStudio.Text.VirtualSnapshotPoint point) [0x00000] in /Users/runner/runners/2.165.0/work/1/s/main/external/vs-editor-core/src/Editor/Text/Impl/BaseViewImpl/TextSelection.cs:350 
  at Microsoft.VisualStudio.Text.Editor.Implementation.TextSelection.Select (Microsoft.VisualStudio.Text.VirtualSnapshotPoint anchorPoint, Microsoft.VisualStudio.Text.VirtualSnapshotPoint activePoint) [0x00069] in /Users/runner/runners/2.165.0/work/1/s/main/external/vs-editor-core/src/Editor/Text/Impl/BaseViewImpl/TextSelection.cs:156 
  at Vim.TextViewUtil.Select (Microsoft.VisualStudio.Text.Editor.ITextView textView, Microsoft.VisualStudio.Text.VirtualSnapshotPoint caretPoint, Microsoft.VisualStudio.Text.VirtualSnapshotPoint anchorPoint, Microsoft.VisualStudio.Text.VirtualSnapshotPoint activePoint) [0x00050] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$CoreInterfaces+selectVirtualSpan@2075.Invoke (Microsoft.VisualStudio.Text.VirtualSnapshotPoint startPoint, Microsoft.VisualStudio.Text.VirtualSnapshotPoint endPoint) [0x0004e] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0000c] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$CoreInterfaces+selectSpan@2087.Invoke (Microsoft.VisualStudio.Text.SnapshotPoint startPoint, Microsoft.VisualStudio.Text.SnapshotPoint endPoint) [0x0000e] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0000c] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.VisualSpan.Select (Microsoft.VisualStudio.Text.Editor.ITextView textView, Vim.SearchPath path) [0x00096] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.Modes.Visual.SelectionTracker.Start () [0x000a8] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.Modes.Visual.SelectionTracker.Vim-Modes-Visual-ISelectionTracker-Start () [0x00019] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.Modes.Visual.VisualMode.OnEnter (Vim.ModeArgument modeArgument) [0x00014] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.Modes.Visual.VisualMode.Vim-IMode-OnEnter (Vim.ModeArgument modeArgument) [0x00000] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$VimBuffer+switchModeCore@115.Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x0013f] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.ModeMap.SwitchMode (Vim.ModeKind kind, Vim.ModeArgument arg) [0x00029] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.VimBuffer.OnVimTextBufferSwitchedMode (Vim.ModeKind modeKind, Vim.ModeArgument modeArgument) [0x0002b] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$VimBuffer+-ctor@233-192.Invoke (Vim.SwitchModeKindEventArgs args) [0x0001c] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Microsoft.FSharp.Control.CommonExtensions+SubscribeToObservable@1722[T].System-IObserver`1-OnNext (T args) [0x00000] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers+h@349[TArgs].Invoke (System.Object _arg1, TArgs args) [0x00000] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0000c] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$VimBuffer+-ctor@232-191.Invoke (System.Object delegateArg0, Vim.SwitchModeKindEventArgs delegateArg1) [0x00000] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 
   --- End of inner exception stack trace ---
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:409 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Reflection/MethodBase.cs:53 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e1] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/Delegate.cs:465 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/MulticastDelegate.cs:67 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/Delegate.cs:410 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x0001b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/MulticastDelegate.cs:72 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/System/Delegate.cs:410 
  at Microsoft.FSharp.Control.FSharpDelegateEvent`1[TDelegate].Trigger (System.Object[] args) [0x0000a] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.StandardEvent`1[T].Trigger (System.Object sender, T args) [0x0001c] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.VimTextBuffer.SwitchMode (Vim.ModeKind modeKind, Vim.ModeArgument modeArgument) [0x0001a] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.VimTextBuffer.Vim-IVimTextBuffer-SwitchMode (Vim.ModeKind modeKind, Vim.ModeArgument modeArgument) [0x00006] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$VimBuffer+switchModeCore@115.Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00133] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.ModeMap.SwitchMode (Vim.ModeKind kind, Vim.ModeArgument arg) [0x00029] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.VimBuffer.SwitchMode (Vim.ModeKind modeKind, Vim.ModeArgument modeArgument) [0x00024] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.VimBuffer.Vim-IVimBuffer-SwitchMode (Vim.ModeKind kind, Vim.ModeArgument arg) [0x0001f] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$SelectionChangeTracker+doUpdate@184-1.Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00107] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at Vim.Mac.VimCocoaHost.DoActionWhenTextViewReady (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] action, Microsoft.VisualStudio.Text.Editor.ITextView textView) [0x00001] in <e814f1c637fa41fcad63b054bf9e9fd6>:0 
  at Vim.CommonOperations.DoActionWhenReady (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] action) [0x00029] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at <StartupCode$Vim-Core>.$CommonOperations+DoActionAsync@219.Invoke (System.Object _arg3) [0x00002] in <5e4b9fb5b6bc8869a7450383b59f4b5e>:0 
  at MonoDevelop.Ide.DispatchService+GtkSynchronizationContext+TimeoutProxy.HandlerInternal (System.IntPtr data) [0x00014] in /Users/runner/runners/2.165.0/work/1/s/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs:78 
WARNING [2020-03-08 13:56:27Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
WARNING [2020-03-08 13:56:27Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
WARNING [2020-03-08 13:56:27Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
INFO [2020-03-08 13:56:42Z]: AMDevice: Aaron iPhone 11 Pro: 00008030-00154DE90C40802E
WARNING [2020-03-08 13:57:02Z]: Failed to get filename of textbuffer, breakpoints integration will not work.
INFO [2020-03-08 13:58:05Z]: AMDevice: Aaron iPhone 11 Pro: 00008030-00154DE90C40802E
WARNING [2020-03-08 13:58:20Z]: Failed to get filename of textbuffer, breakpoints integration will not work.

**Comment by nosami** [comment]
@aaronlabeau That's great! I can see how to fix that.

**Comment by nosami** [comment]
I jumped the gun a little and already published my fix as 2.8.0.3 for VSMac 8.4

Please try it out and see if it is working for you. Thanks!

**Comment by nosami** [comment]
@idchlife this bug got auto-closed but feel free to re-open if the fix isn't working for you. Cheers!

**Comment by aaronlabeau** [comment]
@nosami so far this is working without issues.  I'll be testing a lot tonight - I'll let you know.

**Comment by idchlife** [comment]
@aaronlabeau how is it going? No problems so far?

@nosami unfortunately problem stayed D: I experienced it more than often in the last 5-10 days. Only restart helps.

Also, I may suspect that problem possibly comes from the fact that my system has 2 languages, and I sometimes forget to switch languages. Maybe then something breaks, who knows.

I will try to investigate more and will write here
