### ISSUE TITLE
[VSMac] TypeLoadException when trying to host this extension with .NET Core

### ISSUE THREAD

**Issue by nosami** [VsVim/VsVim#2934]
**Describe the bug**

When trying to load this extension using a .Net core process, the following exception is observed.

```
System.TypeLoadException: Could not load type 'System.Windows.Threading.DispatcherTimer' from assembly 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Vim.UI.Wpf.Implementation.Misc.KeyMappingTimeoutHandler.TimerData..ctor(IVimBuffer vimBuffer, IProtectedOperations protectedOperations, KeyMappingTimeoutHandler keyMappingTimeoutHandler)
   at Vim.UI.Wpf.Implementation.Misc.KeyMappingTimeoutHandler.OnVimBufferCreated(IVimBuffer vimBuffer) in Vim.Mac.dll:token 0x6000151+0x7
   at Vim.UI.Wpf.Implementation.Misc.KeyMappingTimeoutHandler.Vim.IVimBufferCreationListener.VimBufferCreated(IVimBuffer vimBuffer) in Vim.Mac.dll:token 0x6000153+0x1
   at <StartupCode$Vim-Core>.$Vim.NotifyListeners@629.Invoke(Lazy`1 x) in Vim.Core.dll:token 0x6002935+0x0
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in Vim.Core.dll:token 0x60058d0+0x25
   at Vim.VimImpl.CreateVimBuffer(ITextView textView, FSharpOption`1 windowSettings) in Vim.Core.dll:token 0x600270f+0x1f
   at Vim.VimImpl.GetOrCreateVimBuffer(ITextView textView) in Vim.Core.dll:token 0x6002713+0x2b
   at Vim.VimImpl.Vim.IVim.GetOrCreateVimBuffer(ITextView textView) in Vim.Core.dll:token 0x6002748+0x15
   at VimHost.DefaultKeyProcessorProvider.GetAssociatedProcessor(ICocoaTextView cocoaTextView) in Vim.Mac.dll:token 0x6000005+0x1d
   at Microsoft.VisualStudio.Text.Editor.Implementation.InputController.<UpdateKeyProcessors>b__8_0(IKeyProcessorProvider p) in /Users/jasonimison/src/vsmac/main/external/VS-Platform/src/Editor/Text/ImplCocoa/CocoaView/InputImpl/InputController.cs:line 121
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter) in /Users/jasonimison/src/vsmac/main/external/VS-Platform/src/Editor/Text/Util/TextDataUtil/GuardedOperations.cs:line 409
```

**Comment by jaredpar** [comment]
How are you thinking about approaching this? 

When I was thinking about this over the weekend the rough idea I had in my head was to:

- Multi-target between: `net472` and `net6.0` (or whatever TF is most appropriate for VS4Mac here).
- Have two `<ItemGroup>` for the `<Reference>` set in `VimCore` and condition them on the TF. That should allow us to control the references passed in each TF pretty easily. 

That should get us past the `VimCore` layer which is likely the hardest one here. I'm unsure though where the proper reference assemblies live for the VS editor layer are though.

**Comment by nosami** [comment]
I haven't spent any time thinking about this yet but your idea sounds good.

I believe that multi-targeting support in VSMac isn't quite as well baked yet as it is in Windows so I'll just have to try it and see.

This is another of those issues that only affects me at this moment in time although I do want to get it done as soon as possible.

**Comment by nosami** [comment]
Fixed by https://github.com/VsVim/VsVim/pull/2963
