### ISSUE TITLE
System.InvalidOperationException: The location specified is outside the buffer

### ISSUE THREAD

**Issue by nosami** [VsVim/VsVim#2956]
I have no idea what I did to cause this exception. I've never seen it before.

I saw this exception in VSMac, but it looks like this bug might not be Mac specific.

The ExtensionErrorHandler caught this and didn't crash the IDE. I probably wouldn't have even noticed if I wasn't debugging the IDE at the time.

```
System.InvalidOperationException: The location specified is outside the buffer
   at Vim.SnapshotColumn.Add(Int32 count)
   at Vim.SnapshotPointUtil.getRelativeColumn@2541.Invoke(Int32 direction, FSharpFunc`2 isEnd)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at Vim.SnapshotPointUtil.GetRelativeColumn(SnapshotColumn column, Int32 count, Boolean skipLineBreaks)
   at Vim.MotionUtil.CharRightWithLineWrap(Int32 count)
   at Vim.MotionUtil.CharMotion(Int32 count, Boolean withLineWrap)
   at Vim.MotionUtil.SpaceRight(Int32 count)
   at Vim.MotionUtil.GetMotion(Motion motion, MotionArgument motionArgument)
   at Vim.MotionUtil.Vim.IMotionUtil.GetMotion(Motion motion, MotionArgument motionArgument)
   at Vim.CommandUtil.MoveCaretToMotion(Motion motion, FSharpOption`1 count)
   at Vim.CommandUtil.RunNormalCommandCore(NormalCommand command, CommandData data)
   at <StartupCode$Vim-Core>.$CommandUtil.RunNormalCommand@3015.Invoke(Unit unitVar0)
   at Vim.CommonOperations.RunForAllSelections(FSharpFunc`2 action)
   at Vim.CommonOperations.Vim.ICommonOperations.RunForAllSelections(FSharpFunc`2 action)
   at Vim.CommandUtil.RunNormalCommand(NormalCommand command, CommandData data)
   at Vim.CommandUtil.RunCommand(Command command)
   at Vim.CommandUtil.Vim.ICommandUtil.RunCommand(Command command)
   at Vim.CommandRunner.Run(KeyInput ki)
   at Vim.CommandRunner.Vim.ICommandRunner.Run(KeyInput ki)
   at Vim.Modes.Normal.NormalMode.Process(KeyInputData keyInputData)
   at Vim.Modes.Normal.NormalMode.Vim.IMode.Process(KeyInputData keyInputData)
   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput, Boolean wasMapped)
   at <StartupCode$Vim-Core>.$VimBuffer.processSet@632.Invoke(KeyInputSet keyInputSet, Boolean wasMapped)
   at Microsoft.FSharp.Core.FSharpFunc`2.InvokeFast[V](FSharpFunc`2 func, T arg1, TResult arg2)
   at <StartupCode$Vim-Core>.$VimBuffer.processMappedSet@638.Invoke(KeyInputSet keyInputSet)
   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)
   at Vim.VimBuffer.Process(KeyInput keyInput)
   at Vim.VimBuffer.Vim.IVimBuffer.Process(KeyInput keyInput)
   at Vim.UI.Cocoa.VimKeyProcessor.TryProcess(KeyEventArgs e, KeyInput keyInput)
   at Vim.UI.Cocoa.VimKeyProcessor.KeyDown(KeyEventArgs e)
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchKeyEvents>b__6_3(KeyProcessor p, KeyEventArgs e) in /Users/runner/work/1/s/src/Editor/Text/ImplCocoa/CocoaView/InputImpl/KeyProcessorDispatcher.cs:line 34
   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass7_1.<Dispatch>b__0() in /Users/runner/work/1/s/src/Editor/Text/ImplCocoa/CocoaView/InputImpl/KeyProcessorDispatcher.cs:line 46
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) in /Users/runner/work/1/s/src/Editor/Text/Util/TextDataUtil/GuardedOperations.cs:line 534
```

**Comment by jaredpar** [comment]
Generally this type of error happens when one of the two following happen:

1. VsVim recorded a location, triggered an event, another extension did an edit based off the event, then VsVim used the location that is now invalid 
2. VsVim forgot to properly map a location between projection buffers

I think (1) is most likely here because projection buffer errors usually get found pretty fast. Wonder what event is getting triggered here that someone else is hooking. 

The solution is usually to just record the location later or use a tracking location to map the point across the edits.

**Comment by nosami** [comment]
I've assigned it to myself but will probably just close this in a few days if I don't manage to reproduce it again.

**Comment by nosami** [comment]
I haven't seen this error since so closing as non-actionable.
