### ISSUE TITLE
Relative Numbers margin does not display on bleeding edge builds of VSMac

### ISSUE THREAD

**Issue by nosami** [VsVim/VsVim#2960]
**Describe the bug**
The Relative numbers margin does not display and the following exception can be observed whilst debugging.

It looks as if the type `System.nfloat` has been moved to a different assembly, maybe a rebuild against the bleeding edge VSMac will fix this. The problem with this is that it would be broken for anybody on an earlier preview of VSMac.

```
WARNING [2022-02-23 15:00:51Z]: VsVim: Failed to get filename of textbuffer.
   at Vim.UI.Cocoa.Implementation.RelativeLineNumbers.RelativeLineNumbersMargin..ctor(ICocoaTextView textView, ICocoaClassificationFormatMap classificationFormatMap, IClassificationTypeRegistryService classificationTypeRegistry, IVimLocalSettings vimLocalSettings)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter) in /Users/runner/work/1/s/src/Editor/Text/Util/TextDataUtil/GuardedOperations.cs:line 520
   at Microsoft.VisualStudio.Editor.Implementation.ExtensionErrorHandler.Fail(System.String message)
   at Microsoft.VisualStudio.Editor.Implementation.ExtensionErrorHandler.HandleError(System.Object sender, System.Exception exception)
   at Microsoft.VisualStudio.Text.Utilities.CocoaContainerMargin.<AddMargins>b__32_1(ICocoaTextViewMarginProvider mp) in /Users/runner/work/1/s/src/Editor/Text/ImplCocoa/CocoaView/TextUIUtil/ContainerMargin.cs:line 301
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension(System.Object errorSource, System.Lazy`2 provider, System.Func`2 getter)
   at Microsoft.VisualStudio.Text.Utilities.CocoaContainerMargin.AddMargins(IList`1 providers, System.Collections.Generic.List`1 oldMargins)
   at Microsoft.VisualStudio.Text.Utilities.CocoaContainerMargin.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.LeftSelectionMarginProvider.CreateMargin(ICocoaTextViewHost textViewHost, ICocoaTextViewMargin containerMargin)
   at Microsoft.VisualStudio.Text.Utilities.CocoaContainerMargin.<AddMargins>b__32_1(ICocoaTextViewMarginProvider mp)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CocoaLeftSelectionMargin.Create(ICocoaTextViewHost textViewHost, IEditorOperations editorOperations, Microsoft.VisualStudio.Text.Utilities.GuardedOperations guardedOperations, Microsoft.VisualStudio.Text.Utilities.CocoaTextViewMarginState marginState)
ERROR [2022-02-23 15:00:51Z]: Failed assertion: System.TypeLoadException: Could not load type 'System.nfloat' from assembly 'Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.
   at Microsoft.VisualStudio.Text.Editor.Implementation.CocoaLeftMargin.Create(ICocoaTextViewHost textViewHost, Microsoft.VisualStudio.Text.Utilities.GuardedOperations guardedOperations, Microsoft.VisualStudio.Text.Utilities.CocoaTextViewMarginState marginState)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension(System.Object errorSource, System.Lazy`2 provider, System.Func`2 getter)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.HandleException(System.Object errorSource, System.Exception e)
   at MonoDevelop.TextEditor.CocoaTextViewContent.CreateControl()
   at Vim.UI.Cocoa.Implementation.RelativeLineNumbers.RelativeLineNumbersMarginFactory.CreateMargin(ICocoaTextViewHost wpfTextViewHost, ICocoaTextViewMargin marginContainer)
   at Microsoft.VisualStudio.Text.Utilities.CocoaContainerMargin.AddMargins(IList`1 providers, System.Collections.Generic.List`1 oldMargins)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CocoaTextEditorFactoryService.CreateTextViewHost(ICocoaTextView cocoaTextView, Boolean setFocus)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CocoaTextViewHost..ctor(ICocoaTextView textView, Boolean setFocus, Microsoft.VisualStudio.Text.Editor.Implementation.CocoaTextEditorFactoryService factory, Boolean initialize)
   at Microsoft.VisualStudio.Text.Utilities.CocoaContainerMargin.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.CocoaTextViewHost.Initialize()
   at MonoDevelop.TextEditor.TextViewContent`2+<OnGetViewControlAsync>d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(System.Runtime.CompilerServices.TStateMachine ByRef stateMachine)
   at MonoDevelop.Ide.Gui.Documents.DocumentController.OnGetViewControlCallback(CancellationToken token)
   at MonoDevelop.Ide.Gui.Documents.DocumentViewContent.LoadControl(CancellationToken cancellationToken)
   at VisualStudioMac.UI.Shell.CocoaShellDocumentViewContent.OnLoad(CancellationToken cancellationToken)
   at VisualStudioMac.UI.Shell.CocoaShellDocumentViewContent+<OnLoad>d__26.MoveNext()
   at MonoDevelop.TextEditor.TextViewContent`2.OnGetViewControlAsync(CancellationToken token, MonoDevelop.Ide.Gui.Documents.DocumentViewContent view)
   at VisualStudioMac.UI.Shell.CocoaShellDocumentViewItem+<>c__DisplayClass32_0.<LoadView>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(System.Runtime.CompilerServices.TStateMachine ByRef stateMachine)
   at MonoDevelop.Ide.Gui.Documents.DocumentViewContent+<LoadControl>d__19.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(System.Runtime.CompilerServices.TStateMachine ByRef stateMachine)
   at VisualStudioMac.UI.Shell.CocoaShellDocumentViewItem.Load(CancellationToken cancellationToken)
   at VisualStudioMac.UI.Shell.CocoaShellDocumentView.ViewDidMoveToSuperview()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object target, Span`1 ByRef arguments, System.Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
   at ObjCRuntime.Runtime.InvokeMethod(System.Reflection.MethodBase method, System.Object instance, IntPtr native_parameters)
   at ObjCRuntime.Runtime.InvokeMethod(ObjCRuntime.MonoObject* methodobj, ObjCRuntime.MonoObject* instanceobj, IntPtr native_parameters)
   at ObjCRuntime.Runtime.bridge_runtime_invoke_method(ObjCRuntime.MonoObject* method, ObjCRuntime.MonoObject* instance, IntPtr parameters, IntPtr ByRef exception_gchandle)
   at ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle(IntPtr receiver, IntPtr selector, NativeHandle arg1)
   at ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle(IntPtr receiver, IntPtr selector, NativeHandle arg1)
   at AppKit.NSView.AddSubview(AppKit.NSView aView)
   at VisualStudioMac.UI.LayoutExtensions.AddChildToParentAndFill(AppKit.NSView parent, AppKit.NSView child)
   at VisualStudioMac.UI.Shell.CocoaSdiWorkspaceWindow.SetRootView(IShellDocumentViewItem view)
```

**Comment by nosami** [comment]
This was fixed by https://github.com/VsVim/VsVim/pull/2963
